---
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0

  - hooks:
      - id: isort
        name: isort (python code formatter)
    repo: https://github.com/PyCQA/isort
    rev: 5.13.2

  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 24.4.2

  - hooks:
      - id: pyproject-flake8
    repo: https://github.com/csachs/pyproject-flake8
    rev: v7.0.0

  - hooks:
      - id: bandit
    repo: https://github.com/PyCQA/bandit
    rev: 1.7.9

  # - hooks:
  #     - id: numpydoc-validation
  #   repo: https://github.com/numpy/numpydoc
  #   rev: v1.7.0

  - hooks:
      - id: shellcheck
    repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1

  - hooks:
      - id: mdformat
    repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17

  - hooks:
      - id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
